<?php

$userController = new UsuarioController();
$userController->store([
    'id_wappersonas' =>  1,
    'nombre' => 'Estefi',
    'apellido' => 'Fernandez',
    'telefono' => '299569874',
    'dni' => 36256251,
    'genero' => 'H',
    'email' => 'Estefio@gmail.com',
    'nacionalidad' => 'Argentino',
    'id_ciudad' => 1,
    'id_barrio' => 1,
    'id_zona' => 3,
    'direccion_calle' => 'Lugar',
    'direccion_nro' => '748',
    'direccion_depto' => 'SI',
    'direccion_piso' => '8300',
    'direccion_cp' => '8300',
]);
$userController->store([
    'id_wappersonas' =>  2,
    'nombre' => 'Juan',
    'apellido' => 'Gabriel',
    'telefono' => '299569874',
    'dni' => 36256251,
    'genero' => 'H',
    'email' => 'Juan@gmail.com',
    'nacionalidad' => 'Argentino',
    'id_ciudad' => 1,
    'id_barrio' => 1,
    'id_zona' => 3,
    'direccion_calle' => 'Lugar',
    'direccion_nro' => '748',
    'direccion_depto' => 'SI',
    'direccion_piso' => '8300',
    'direccion_cp' => '8300',
]);
$userController->store([
    'id_wappersonas' =>  3,
    'nombre' => 'Kiol',
    'apellido' => 'Pedro',
    'telefono' => '299569874',
    'dni' => 36256251,
    'genero' => 'H',
    'email' => 'Kiol@gmail.com',
    'nacionalidad' => 'Argentino',
    'id_ciudad' => 1,
    'id_barrio' => 1,
    'id_zona' => 3,
    'direccion_calle' => 'Lugar',
    'direccion_nro' => '748',
    'direccion_depto' => 'SI',
    'direccion_piso' => '8300',
    'direccion_cp' => '8300',
]);
